# Generated by Django 4.2.7 on 2024-10-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapi', '0003_alter_prediction_prediction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
